# Generated by Django 6.0.7 on 2026-07-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_note',
            field=models.TextField(blank=True, help_text='Message printed for gift orders'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
