# Generated by Django 5.2.6 on 2026-08-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_whatsapp_leads_and_order_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplead',
            name='status',
            field=models.CharField(choices=[('true_enquiry', 'True enquiry')], db_index=True, default='true_enquiry', max_length=20),
        ),
    ]
