# Generated by Django 5.2.6 on 2026-08-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_whatsapp_lead_true_enquiry_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplead',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting review'), ('true_enquiry', 'True enquiry')], db_index=True, default='pending', max_length=20),
        ),
    ]
