# Generated by Django 5.2.6 on 2026-08-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='active_session_key',
            field=models.CharField(blank=True, default='', help_text='Exclusive client session key; empty for signed-out or admin users.', max_length=40),
        ),
    ]
