# Generated by Django 6.0.7 on 2026-07-31 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepage',
            options={'ordering': ['title']},
        ),
    ]
