# Generated by Django 6.0.7 on 2026-07-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Shade swatch as a hex colour, e.g. #A94F5C', max_length=7),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/variants/%Y/%m/'),
        ),
    ]
